version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.15.2
    depends_on:
      - db
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:root@db:5432/subscriptions?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/db/migrations:/migrations

  app:
    build: .
    depends_on:
      - migrate
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  db_data:
